import pickle
import matplotlib.pyplot as plt

sex=pickle.load(open('sex_nn_result.pkl'))
#sex['loss']
#sex['acc']

bio=pickle.load(open('bio_nn_result.pkl'))
#bio['loss']
#bio['acc']
fig = plt.figure(frameon=False)
fig.set_size_inches(6, 4)
plt.grid()
    # fig = pylab.figure()
ax = fig.add_subplot(1, 1, 1)
ax.yaxis.grid(color='gray', linestyle='dashed')
ax.xaxis.grid(color='gray', linestyle='dashed')
plt.plot(sex['loss'][0],'-ro', label="lr=0.0001")
plt.plot(sex['loss'][1],'-go', label="lr=0.0005")
plt.plot(sex['loss'][2],'-bo', label="lr=0.001")
plt.plot(sex['loss'][3],'-yo', label="lr=0.01")
plt.plot(sex['loss'][4],'-co', label="lr=0.03")
plt.title('influence of lr in Sex-2 task')
#plt.plot(history.history['val_acc'])
plt.xlabel('epoch')
plt.ylabel('Loss')
# plt.legend(loc='lower right')
plt.legend()
plt.savefig('lr_loss_sex.pdf')
plt.show()
# summarize history for loss
fig = plt.figure(frameon=False)
fig.set_size_inches(6, 4)


plt.grid()
    # fig = pylab.figure()
ax = fig.add_subplot(1, 1, 1)
ax.yaxis.grid(color='gray', linestyle='dashed')
ax.xaxis.grid(color='gray', linestyle='dashed')
plt.plot(sex['acc'][0],'-ro', label="lr=0.0001")
plt.plot(sex['acc'][1],'-go', label="lr=0.0005")
plt.plot(sex['acc'][2],'-bo', label="lr=0.001")
plt.plot(sex['acc'][3],'-yo', label="lr=0.01")
plt.plot(sex['acc'][4],'-co', label="lr=0.03")
plt.title('influence of lr in Sex-2 task')
#plt.plot(history.history['val_acc'])
plt.xlabel('epoch')
plt.ylabel('Accuracy')
plt.legend(loc='lower right')
# plt.legend()
plt.savefig('lr_acc_sex.pdf')
plt.show()

plt.grid()
    # fig = pylab.figure()
ax = fig.add_subplot(1, 1, 1)
ax.yaxis.grid(color='gray', linestyle='dashed')
ax.xaxis.grid(color='gray', linestyle='dashed')
plt.plot(bio['loss'][0],'-ro', label="lr=0.0001")
plt.plot(bio['loss'][1],'-go', label="lr=0.0005")
plt.plot(bio['loss'][2],'-bo', label="lr=0.001")
plt.plot(bio['loss'][3],'-yo', label="lr=0.01")
plt.plot(bio['loss'][4],'-co', label="lr=0.03")
plt.title('influence of lr in BioSourceType-7 task')
#plt.plot(history.history['val_acc'])
plt.xlabel('epoch')
plt.ylabel('Loss')
# plt.legend(loc='lower right')
plt.legend()
plt.savefig('lr_loss_bio.pdf')
plt.show()
# summarize history for loss
fig = plt.figure(frameon=False)
fig.set_size_inches(6, 4)

plt.grid()
    # fig = pylab.figure()
ax = fig.add_subplot(1, 1, 1)
ax.yaxis.grid(color='gray', linestyle='dashed')
ax.xaxis.grid(color='gray', linestyle='dashed')
plt.plot(bio['acc'][0],'-ro', label="lr=0.0001")
plt.plot(bio['acc'][1],'-go', label="lr=0.0005")
plt.plot(bio['acc'][2],'-bo', label="lr=0.001")
plt.plot(bio['acc'][3],'-yo', label="lr=0.01")
plt.plot(bio['acc'][4],'-co', label="lr=0.03")
plt.title('influence of lr in BioSourceType-7 task')
#plt.plot(history.history['val_acc'])
plt.xlabel('epoch')
plt.ylabel('Accuracy')
# plt.legend(loc='upper right')
plt.legend()
plt.savefig('lr_acc_bio.pdf')
plt.show()